### ISSUE TITLE
Error: index out of range

### ISSUE THREAD

**Issue by dlinch** [Arkweid/lefthook#28] opened 2019-07-12 16:20 UTC
Hi there, I stumbled upon this project from a cool EvilMartians blog [post](https://dev.to/evilmartians/lefthook-crystalball-and-git-magic-for-smooth-development-experience-33mc).

I went to implement in my own project, and I tried both the homebrew binary and the Node module, and when I run `lefthook install` or `yarn lefthook install` I get the same error:
`runtime error: index out of range`

All I have done at this point is create the `lefthook.yml` file and download the binary, so I'm petty sure I'm not doing anything wrong.

**Comment by Arkweid** [comment] 2019-07-12 19:08
Hello @dlinch. Thank you for issue.
Lets figure out what is going on. The message looks like internal golang error.
Tell me your version.
```
lefthook version
```
Then give me example of `lefthook.yml` file
Also try to delete all files from `.git/hooks` directory and run `lefthook install` again.

**Comment by dlinch** [comment] 2019-07-12 19:38
Lefthook version: 0.6.0

lefthook.yml:
```
pre-push:
  parallel: true
  commands:
    rubocop:
      tags: backend
      run: if [[ `git status --porcelain |egrep '^A|^M' |egrep '\\.ts'` ]]; then yarn lint; fi && git status --porcelain |egrep '^A|^M' |grep '.rb' |awk '{print $2}' |xargs bundle exec rubocop
    rspec:
      tags: rspec backend
      run: bundle exec crystalball --fail-fast
```


So removing everything from .git/hooks seemed to do the trick. I did have an implementation with Husky that I was porting over into lefthook. Is there a reason why having content inside the hooks would make lefthook fail? It seems like it should be able to handle that. Probably by overwriting the hooks defined in `lefthook.yml`

**Comment by Arkweid** [comment] 2019-07-12 20:24
Ye, and lefthook does it. I've tried to reproduce the issue, but unfortunately all works as expected. :(

Also we have migration guide: https://github.com/Arkweid/lefthook/wiki/Migration-from-husky
When you uninstall husky it should delete all that files:
![husky_files](https://i.gyazo.com/3e9761dd33625820951099c2d3f3e599.png)

But even if husky doesn't do it, so lefthook should rewrite necessary files. If you know how to reproduce that let me know. I investigate the problem.

**Comment by dlinch** [comment] 2019-07-12 20:40
Ahh, I didn't explicitly run `yarn remove husky`, as I'm spiking on this and I didn't want to actually remove the dependency for when I switch back to my main branch.

Reproduce steps:
- I had Husky locally, which has all the git hooks prepopulated:

![Screen Shot 2019-07-12 at 2 38 20 PM](https://user-images.githubusercontent.com/5693184/61157232-c2274c00-a4b2-11e9-99b3-9e6289f9cda8.png)

- Run `yarn @arkweid/lefthook -D`
- Populate `lefthook.yml`
- Run `lefthook install`

![Screen Shot 2019-07-12 at 2 40 41 PM](https://user-images.githubusercontent.com/5693184/61157320-0d415f00-a4b3-11e9-84fb-d4ac2d27c0f8.png)

I noticed that Husky creates a hook for all possible hooks in git, but lefthook only creates them for hooks that were specified. Perhaps that discrepancy is a good place to start?

**Comment by Arkweid** [comment] 2019-07-12 21:14
Can't reproduce it on Mint and Ubuntu. :/
With same flow I've got expected behavior.
![pic](https://cdn1.savepice.ru/uploads/2019/7/13/dc1e52038a279440518ed610ae5f9e31-full.png)

Maybe something wrong with Mac version. Ok, I will check it. Thanks for your comment @dlinch!

**Comment by dlinch** [comment] 2019-07-12 21:37
No problem! Yeah I'm on Mac.

**Comment by Arkweid** [comment] 2019-07-15 13:55
Fixed in next version.

**Closed by Arkweid** 2019-07-15 13:55 UTC
Labels: bug
